server {
    listen 80;
    listen [::]:80;
    server_name cartilla.plcommsdash.site;
    return 301 https://cartilla.osmedicaafiliaciones.com$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name cartilla.plcommsdash.site;

    ssl_certificate /etc/letsencrypt/live/plcommsdash.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/plcommsdash.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://cartilla.osmedicaafiliaciones.com$request_uri;
}
